# Generated by Django 3.2.13 on 2022-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNews', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=45)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField()),
                ('Newspaper', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
