# Generated by Django 3.2.13 on 2022-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Keyword',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
